# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 598)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 770, 428))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 25))
        self.menubar.setObjectName("menubar")
        self.menuAcciones = QtWidgets.QMenu(self.menubar)
        self.menuAcciones.setObjectName("menuAcciones")
        self.menuSalas_de_Chat = QtWidgets.QMenu(self.menuAcciones)
        self.menuSalas_de_Chat.setObjectName("menuSalas_de_Chat")
        self.menuMensajes = QtWidgets.QMenu(self.menubar)
        self.menuMensajes.setObjectName("menuMensajes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVer_Usuarios = QtWidgets.QAction(MainWindow)
        self.actionVer_Usuarios.setObjectName("actionVer_Usuarios")
        self.actionCrear_nueva = QtWidgets.QAction(MainWindow)
        self.actionCrear_nueva.setObjectName("actionCrear_nueva")
        self.actionInvitar_usuario_a_sala = QtWidgets.QAction(MainWindow)
        self.actionInvitar_usuario_a_sala.setObjectName("actionInvitar_usuario_a_sala")
        self.actionUnirse_a_sala = QtWidgets.QAction(MainWindow)
        self.actionUnirse_a_sala.setObjectName("actionUnirse_a_sala")
        self.actionMandar_Mensaje_Privado = QtWidgets.QAction(MainWindow)
        self.actionMandar_Mensaje_Privado.setObjectName("actionMandar_Mensaje_Privado")
        self.actionMandar_Mensaje_Publico = QtWidgets.QAction(MainWindow)
        self.actionMandar_Mensaje_Publico.setObjectName("actionMandar_Mensaje_Publico")
        self.actionNuevo_Mensaje_a_Sala = QtWidgets.QAction(MainWindow)
        self.actionNuevo_Mensaje_a_Sala.setObjectName("actionNuevo_Mensaje_a_Sala")
        self.actionCambiar_Status = QtWidgets.QAction(MainWindow)
        self.actionCambiar_Status.setObjectName("actionCambiar_Status")
        self.actionDesconectarse = QtWidgets.QAction(MainWindow)
        self.actionDesconectarse.setObjectName("actionDesconectarse")
        self.menuSalas_de_Chat.addAction(self.actionCrear_nueva)
        self.menuSalas_de_Chat.addAction(self.actionInvitar_usuario_a_sala)
        self.menuSalas_de_Chat.addAction(self.actionUnirse_a_sala)
        self.menuAcciones.addSeparator()
        self.menuAcciones.addAction(self.actionVer_Usuarios)
        self.menuAcciones.addAction(self.menuSalas_de_Chat.menuAction())
        self.menuAcciones.addAction(self.actionCambiar_Status)
        self.menuAcciones.addSeparator()
        self.menuAcciones.addAction(self.actionDesconectarse)
        self.menuMensajes.addAction(self.actionMandar_Mensaje_Privado)
        self.menuMensajes.addAction(self.actionMandar_Mensaje_Publico)
        self.menuMensajes.addAction(self.actionNuevo_Mensaje_a_Sala)
        self.menubar.addAction(self.menuAcciones.menuAction())
        self.menubar.addAction(self.menuMensajes.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.released.connect(self.lineEdit.clear)
        self.lineEdit.returnPressed.connect(self.pushButton.click)
        self.actionMandar_Mensaje_Privado.activated.connect(self.tabWidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat"))
        self.pushButton.setText(_translate("MainWindow", "Enviar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.menuAcciones.setTitle(_translate("MainWindow", "Acciones"))
        self.menuSalas_de_Chat.setTitle(_translate("MainWindow", "Salas de Chat"))
        self.menuMensajes.setTitle(_translate("MainWindow", "Mensajes"))
        self.actionVer_Usuarios.setText(_translate("MainWindow", "Ver Usuarios"))
        self.actionCrear_nueva.setText(_translate("MainWindow", "Crear nueva"))
        self.actionInvitar_usuario_a_sala.setText(_translate("MainWindow", "Invitar usuario a sala"))
        self.actionUnirse_a_sala.setText(_translate("MainWindow", "Unirse a sala"))
        self.actionMandar_Mensaje_Privado.setText(_translate("MainWindow", "Nuevo Mensaje Privado"))
        self.actionMandar_Mensaje_Publico.setText(_translate("MainWindow", "Nuevo Mensaje Publico"))
        self.actionNuevo_Mensaje_a_Sala.setText(_translate("MainWindow", "Nuevo Mensaje a Sala"))
        self.actionCambiar_Status.setText(_translate("MainWindow", "Cambiar Status"))
        self.actionDesconectarse.setText(_translate("MainWindow", "Desconectarse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

